apiVersion: batch/v1
kind: Job
metadata:
  name: "agent-{run_id}-{variation_id}"
  labels:
    app: aideator-agent
    run-id: "{run_id}"
    variation-id: "{variation_id}"
    component: agent
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: aideator-agent
        run-id: "{run_id}"
        variation-id: "{variation_id}"
        component: agent
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: agent
          image: "k3d-registry.localhost:5001/aideator-agent:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: AGENT_MODE
              value: "{agent_mode}"
            - name: REPO_URL
              value: "{repo_url}"
            - name: PROMPT
              value: {prompt}
            - name: TASK_ID
              value: "{task_id}"
            - name: VARIATION_ID
              value: "{variation_id}"
            - name: RUN_ID
              value: "{run_id}"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PYTHONUNBUFFERED
              value: "1"
            # - name: REDIS_URL  # COMMENTED OUT: Redis references removed per user request
            #   value: "redis://aideator-redis:6379/0"
            - name: DATABASE_URL
              value: "postgresql://aideator:aideator123@aideator-database:5432/aideator"
            - name: REQUIRE_API_KEYS_FOR_AGENTS
              value: "false"
            - name: SIMPLE_DEV_MODE
              value: "true"
            - name: DEBUG
              value: "true"
            - name: OPENAI_API_KEY
              value: "{openai_api_key}"
            - name: ANTHROPIC_API_KEY
              value: "{anthropic_api_key}"
            - name: GEMINI_API_KEY
              value: "{gemini_api_key}"
          command: ["python", "-u", "/app/agent/main.py"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      volumes:
        - name: workspace
          emptyDir:
            sizeLimit: 1Gi
