# ctlptl configuration for local k3d cluster
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: aideator-registry
listen: localhost:5005
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: aideator-local
product: k3d
registry: aideator-registry
k3dOptions:
  image: rancher/k3s:v1.28.8-k3s1
  servers: 1
  agents: 1
  ports:
    - port: 8000:30800@server:0  # FastAPI access
    - port: 8080:30080@server:0  # Alternative port
  options:
    - --k3s-arg=--disable=traefik@server:0  # Disable Traefik for simplicity
  volumes:
    - /tmp/k3d-aideator:/tmp/shared@server:0
    - /tmp/k3d-aideator:/tmp/shared@agent:*
  registries:
    - localhost:5005