# BROKEN TEMPLATE - API should NOT read this file anymore
DELIBERATELY_BROKEN_YAML_SHOULD_CAUSE_ERROR_IF_USED
apiVersion: batch/v1
kind: Job
metadata:
  name: "agent-{run_id}-{variation_id}"
  labels:
    app: aideator-agent
    run-id: "{run_id}"
    variation-id: "{variation_id}"
    component: agent
spec:
  ttlSecondsAfterFinished: 3600  # 1 hour cleanup
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: aideator-agent
        run-id: "{run_id}"
        variation-id: "{variation_id}"
        component: agent
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: agent
          image: "aideator-agent:manual-test"
          imagePullPolicy: Never
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api-key
                  optional: true
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: anthropic-secret
                  key: api-key
                  optional: true
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-secret
                  key: api-key
                  optional: true
            - name: MISTRAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mistral-secret
                  key: api-key
                  optional: true
            - name: COHERE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cohere-secret
                  key: api-key
                  optional: true
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: groq-secret
                  key: api-key
                  optional: true
            - name: PERPLEXITY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: perplexity-secret
                  key: api-key
                  optional: true
            - name: DEEPSEEK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: deepseek-secret
                  key: api-key
                  optional: true
            - name: AGENT_MODE
              value: "{agent_mode}"
            - name: REPO_URL
              value: "{repo_url}"
            - name: PROMPT
              value: {prompt}
            - name: VARIATION_ID
              value: "{variation_id}"
            - name: RUN_ID
              value: "{run_id}"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PYTHONUNBUFFERED
              value: "1"
            # SECURITY TRADEOFF: Hardcoded Redis URL for development
            # Production should use service discovery or secrets
            - name: REDIS_URL
              value: "redis://aideator-redis:6379/0"
            # Database URL for agent to write outputs
            - name: DATABASE_URL
              value: "postgresql://aideator:aideator123@aideator-postgresql:5432/aideator"
          command: ["python", "-u", "/app/agent/main.py"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      volumes:
        - name: workspace
          emptyDir:
            sizeLimit: 1Gi
