# Agent job template for dynamic instantiation
apiVersion: batch/v1
kind: Job
metadata:
  name: "agent-{run_id}-{variation_id}"
  labels:
    app: aideator-agent
    run-id: "{run_id}"
    variation-id: "{variation_id}"
    component: agent
spec:
  ttlSecondsAfterFinished: 3600  # 1 hour cleanup
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: aideator-agent
        run-id: "{run_id}"
        variation-id: "{variation_id}"
        component: agent
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: agent
          image: "ctlptl-registry:5000/aideator-agent:dev"
          imagePullPolicy: Always
          env:
            # Secure job token for API key retrieval
            - name: JOB_TOKEN
              value: {job_token}
            # Orchestrator API endpoint for key retrieval
            - name: ORCHESTRATOR_API_URL
              value: "http://aideator-fastapi-svc:8000/api/v1"
            # LiteLLM Gateway configuration
            - name: LITELLM_GATEWAY_URL
              value: "http://chart-aideator-litellm:4000"
            - name: LITELLM_GATEWAY_KEY
              value: "sk-1234"
            # Model configuration
            - name: MODEL
              value: "{model}"
            - name: AGENT_MODE
              value: "{agent_mode}"
            - name: REPO_URL
              value: "{repo_url}"
            - name: PROMPT
              value: {prompt}
            - name: VARIATION_ID
              value: "{variation_id}"
            - name: RUN_ID
              value: "{run_id}"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PYTHONUNBUFFERED
              value: "1"
            # SECURITY TRADEOFF: Hardcoded Redis URL for development
            # Production should use service discovery or secrets
            - name: REDIS_URL
              value: "redis://chart-redis-master:6379/0"
            # Database URL for agent to write outputs
            - name: DATABASE_URL_ASYNC
              value: "postgresql+asyncpg://aideator:aideator123@chart-aideator-postgresql:5432/aideator"
          command: ["python", "-u", "/app/agent/main.py"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      volumes:
        - name: workspace
          emptyDir:
            sizeLimit: 1Gi
