# Agent job template for dynamic instantiation
apiVersion: batch/v1
kind: Job
metadata:
  name: "agent-{run_id}-{variation_id}"
  labels:
    app: aideator-agent
    run-id: "{run_id}"
    variation-id: "{variation_id}"
    component: agent
spec:
  ttlSecondsAfterFinished: 3600  # 1 hour cleanup
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: aideator-agent
        run-id: "{run_id}"
        variation-id: "{variation_id}"
        component: agent
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: agent
          image: "ctlptl-registry:5000/aideator-agent:dev"
          imagePullPolicy: Always
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api-key
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: anthropic-secret
                  key: api-key
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-secret
                  key: api-key
            - name: AGENT_MODE
              value: "{agent_mode}"
            - name: REPO_URL
              value: "{repo_url}"
            - name: PROMPT
              value: "{prompt}"
            - name: VARIATION_ID
              value: "{variation_id}"
            - name: RUN_ID
              value: "{run_id}"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PYTHONUNBUFFERED
              value: "1"
          command: ["python", "-u", "/app/agent/main.py"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      volumes:
        - name: workspace
          emptyDir:
            sizeLimit: 1Gi
