# Batch job template for running multiple agents
apiVersion: batch/v1
kind: Job
metadata:
  name: "batch-{run_id}"
  labels:
    app: aideator-batch
    run-id: "{run_id}"
    component: batch
spec:
  ttlSecondsAfterFinished: 7200  # 2 hours cleanup
  backoffLimit: 2
  parallelism: {parallelism}  # Number of parallel agents
  completions: {completions}  # Total number of agents
  template:
    metadata:
      labels:
        app: aideator-batch
        run-id: "{run_id}"
        component: batch
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: batch-agent
          image: "aideator-agent:dev"
          imagePullPolicy: Always
          env:
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: anthropic-secret
                  key: api-key
            - name: REPO_URL
              value: "{repo_url}"
            - name: PROMPT
              value: {prompt}
            - name: RUN_ID
              value: "{run_id}"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: JOB_COMPLETION_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
          command: ["/bin/sh", "-c"]
          args:
            - |
              VARIATION_ID=${JOB_COMPLETION_INDEX}
              export VARIATION_ID=${VARIATION_ID}
              python -u /app/agent/main.py
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      volumes:
        - name: workspace
          emptyDir: {}
      nodeSelector:
        kubernetes.io/arch: amd64