apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-job-template
  namespace: aideator
data:
  template: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: "agent-{run_id}-{variation_id}"
      labels:
        app: aideator-agent
        run-id: "{run_id}"
        variation-id: "{variation_id}"
        component: agent
    spec:
      ttlSecondsAfterFinished: 3600
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: aideator-agent
            run-id: "{run_id}"
            variation-id: "{variation_id}"
            component: agent
        spec:
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
          containers:
            - name: agent
              image: "aideator-agent:latest"
              imagePullPolicy: Never
              env:
                - name: OPENAI_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: openai-secret
                      key: api-key
                      optional: true
                - name: ANTHROPIC_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: anthropic-secret
                      key: api-key
                      optional: true
                - name: AGENT_MODE
                  value: "{agent_mode}"
                - name: REPO_URL
                  value: "{repo_url}"
                - name: PROMPT
                  value: "{prompt}"
                - name: VARIATION_ID
                  value: "{variation_id}"
                - name: RUN_ID
                  value: "{run_id}"
                - name: LOG_LEVEL
                  value: "INFO"
                - name: PYTHONUNBUFFERED
                  value: "1"
                - name: REDIS_URL
                  value: "redis://aideator-redis:6379/0"
                - name: DATABASE_URL
                  value: "postgresql://aideator:aideator123@aideator-database:5432/aideator"
              command: ["python", "-u", "/app/agent/main.py"]
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "100m"
                limits:
                  memory: "1Gi"
                  cpu: "500m"
              volumeMounts:
                - name: workspace
                  mountPath: /workspace
          volumes:
            - name: workspace
              emptyDir:
                sizeLimit: 1Gi