apiVersion: v1
kind: Service
metadata:
  name: aideator-fastapi-svc
  namespace: aideator
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: fastapi