apiVersion: apps/v1
kind: Deployment
metadata:
  name: aideator-litellm
  namespace: aideator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aideator-litellm
  template:
    metadata:
      labels:
        app: aideator-litellm
    spec:
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:main-stable
        ports:
        - containerPort: 4000
        env:
        - name: OPENAI_API_KEY
          value: "placeholder"
        - name: ANTHROPIC_API_KEY
          value: "placeholder"
        command: ["litellm", "--config", "/app/config.yaml", "--port", "4000"]
        volumeMounts:
        - name: config
          mountPath: /app/config.yaml
          subPath: config.yaml
      volumes:
      - name: config
        configMap:
          name: aideator-litellm-config
---
apiVersion: v1
kind: Service
metadata:
  name: aideator-litellm
  namespace: aideator
spec:
  selector:
    app: aideator-litellm
  ports:
  - port: 4000
    targetPort: 4000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aideator-litellm-config
  namespace: aideator
data:
  config.yaml: |
    model_list:
      - model_name: openai/*
        litellm_params:
          model: openai/*
      - model_name: anthropic/*
        litellm_params:
          model: anthropic/*
      - model_name: gemini/*
        litellm_params:
          model: gemini/*
    general_settings:
      master_key: "dev-key-123"