apiVersion: apps/v1
kind: Deployment
metadata:
  name: aideator-redis
  namespace: aideator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aideator-redis
  template:
    metadata:
      labels:
        app: aideator-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: aideator-redis
  namespace: aideator
spec:
  selector:
    app: aideator-redis
  ports:
  - port: 6379
    targetPort: 6379