# Local development values for AIdeator
replicaCount: 1

image:
  repository: aideator-api
  tag: "dev"
  pullPolicy: Always

agentImage:
  repository: aideator-agent
  tag: "dev"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

# Development configuration
config:
  debug: true
  logLevel: DEBUG
  maxVariations: 3
  apiV1Prefix: /api/v1

# Agent configuration for local development
agents:
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "250m"
  jobTTL: 1800  # 30 minutes for development

# Use PostgreSQL for local development
database:
  type: postgresql
  url: "postgresql+asyncpg://aideator:aideator123@chart-aideator-postgresql:5432/aideator"

# Enable persistence for application data
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""  # Use default storage class

# Resources for local development
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Security context for local development
securityContext:
  runAsNonRoot: false
  runAsUser: 0
  fsGroup: 0

# Environment variables for development
env:
  - name: DEBUG
    value: "true"
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: DATABASE_URL
    value: "postgresql+asyncpg://aideator:aideator123@chart-aideator-postgresql:5432/aideator"
  - name: REDIS_URL
    value: "redis://chart-redis-master:6379/0"

# Enable PostgreSQL for local development
postgresql:
  enabled: true

# Redis configuration override for student project
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false  # In-memory only for development

# LiteLLM Gateway configuration for local development
litellm:
  enabled: true
  database:
    enabled: true
    url: "postgresql://aideator:aideator123@chart-aideator-postgresql:5432/aideator"

# Secrets configuration for local development
secrets:
  anthropic: true
  gemini: true