# Local development values for AIdeator
replicaCount: 1

image:
  repository: aideator-api
  tag: "dev"
  pullPolicy: Always

agentImage:
  repository: aideator-agent
  tag: "dev"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

# Development configuration
config:
  debug: true
  logLevel: DEBUG
  maxVariations: 3
  apiV1Prefix: /api/v1

# Agent configuration for local development
agents:
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "250m"
  jobTTL: 1800  # 30 minutes for development

# Use SQLite with persistent volume
database:
  type: sqlite
  url: "sqlite+aiosqlite:////app/data/aideator.db"

# Enable persistence for SQLite database
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""  # Use default storage class

# Resources for local development
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Security context for local development
securityContext:
  runAsNonRoot: false
  runAsUser: 0
  fsGroup: 0

# Environment variables for development
env:
  - name: DEBUG
    value: "true"
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: DATABASE_URL
    value: "sqlite+aiosqlite:////app/data/aideator.db"