# ConfigMap containing agent job template for dynamic spawning
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aideator.fullname" . }}-agent-job-template
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aideator.labels" . | nindent 4 }}
data:
  agent-job-template.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: "PLACEHOLDER_JOB_NAME"
      labels:
        app: aideator-agent
        task-id: "PLACEHOLDER_TASK_ID"
        variation-id: "PLACEHOLDER_VARIATION_ID"
      ttlSecondsAfterFinished: {{ .Values.agents.jobTTL }}
      template:
        metadata:
          labels:
            app: aideator-agent
            task-id: "PLACEHOLDER_TASK_ID"
            variation-id: "PLACEHOLDER_VARIATION_ID"
        spec:
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
          containers:
            - name: agent
              image: "{{ .Values.agentImage.repository }}:{{ .Values.agentImage.tag }}"
              imagePullPolicy: {{ .Values.agentImage.pullPolicy }}
              env:
                # LiteLLM Gateway configuration
                - name: LITELLM_GATEWAY_URL
                  value: "http://{{ include "aideator.fullname" . }}-litellm:{{ .Values.litellm.service.port | default 4000 }}"
                - name: LITELLM_GATEWAY_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "aideator.fullname" . }}-litellm-secret
                      key: master-key
                - name: MODEL
                  value: "PLACEHOLDER_MODEL"
                # API keys will be injected dynamically by FastAPI
                # Job configuration - will be replaced with actual values
                - name: REPO_URL
                  value: "PLACEHOLDER_REPO_URL"
                - name: PROMPT
                  value: "PLACEHOLDER_PROMPT"
                - name: VARIATION_ID
                  value: "PLACEHOLDER_VARIATION_ID"
                - name: TASK_ID
                  value: "PLACEHOLDER_TASK_ID"
                - name: LOG_LEVEL
                  value: "INFO"
                - name: PYTHONUNBUFFERED
                  value: "1"
                # Database URL for agent output persistence
                - name: DATABASE_URL
                  value: "{{ .Values.database.url }}"
                # Redis URL for real-time streaming
                - name: REDIS_URL
                  value: "redis://{{ include "aideator.fullname" . }}-redis:6379/0"
              command: ["python", "-u", "/app/agent/main.py"]
              resources:
                {{- toYaml .Values.agents.resources | nindent 16 }}
      backoffLimit: 0