# ConfigMap containing agent job template for dynamic spawning
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aideator.fullname" . }}-agent-job-template
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aideator.labels" . | nindent 4 }}
data:
  agent-job-template.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: "PLACEHOLDER_JOB_NAME"
      labels:
        app: aideator-agent
        run-id: "PLACEHOLDER_RUN_ID"
        variation-id: "PLACEHOLDER_VARIATION_ID"
      ttlSecondsAfterFinished: {{ .Values.agents.jobTTL }}
      template:
        metadata:
          labels:
            app: aideator-agent
            run-id: "PLACEHOLDER_RUN_ID"
            variation-id: "PLACEHOLDER_VARIATION_ID"
        spec:
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
          containers:
            - name: agent
              image: "{{ .Values.agentImage.repository }}:{{ .Values.agentImage.tag }}"
              imagePullPolicy: {{ .Values.agentImage.pullPolicy }}
              env:
                # LiteLLM Gateway configuration
                - name: LITELLM_GATEWAY_URL
                  value: "http://{{ include "aideator.fullname" . }}-litellm:{{ .Values.litellm.service.port | default 4000 }}"
                - name: LITELLM_GATEWAY_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "aideator.fullname" . }}-litellm-secret
                      key: master-key
                - name: MODEL
                  value: "PLACEHOLDER_MODEL"
                # API key retrieval system
                - name: JOB_TOKEN
                  value: "PLACEHOLDER_JOB_TOKEN"
                - name: ORCHESTRATOR_API_URL
                  value: "http://aideator-fastapi-svc:{{ .Values.service.port | default 8000 }}/api/v1"
                # Job configuration - will be replaced with actual values
                - name: REPO_URL
                  value: "PLACEHOLDER_REPO_URL"
                - name: PROMPT
                  value: "PLACEHOLDER_PROMPT"
                - name: VARIATION_ID
                  value: "PLACEHOLDER_VARIATION_ID"
                - name: RUN_ID
                  value: "PLACEHOLDER_RUN_ID"
                - name: LOG_LEVEL
                  value: "INFO"
                - name: PYTHONUNBUFFERED
                  value: "1"
                # Required service connections
                - name: REDIS_URL
                  value: "redis://chart-redis-master:6379"
                - name: DATABASE_URL_ASYNC
                  value: "postgresql+asyncpg://aideator:aideator123@chart-aideator-postgresql:5432/aideator"
              command: ["python", "-u", "/app/agent/main.py"]
              resources:
                {{- toYaml .Values.agents.resources | nindent 16 }}
      backoffLimit: 0