# Template for agent jobs - instantiated by FastAPI
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.agentJobName | default "agent-job" }}"
  labels:
    app: aideator-agent
    run-id: "{{ .Values.runId | default "unknown" }}"
    variation-id: "{{ .Values.variationId | default "0" }}"
spec:
  ttlSecondsAfterFinished: {{ .Values.agents.jobTTL }}
  template:
    metadata:
      labels:
        app: aideator-agent
        run-id: "{{ .Values.runId | default "unknown" }}"
        variation-id: "{{ .Values.variationId | default "0" }}"
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: agent
          image: "{{ .Values.agentImage.repository }}:{{ .Values.agentImage.tag }}"
          imagePullPolicy: {{ .Values.agentImage.pullPolicy }}
          env:
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.anthropic.name }}
                  key: {{ .Values.secrets.anthropic.key }}
            - name: REPO_URL
              value: "{{ .Values.repoUrl | default "" }}"
            - name: PROMPT
              value: "{{ .Values.prompt | default "" }}"
            - name: VARIATION_ID
              value: "{{ .Values.variationId | default "0" }}"
            - name: RUN_ID
              value: "{{ .Values.runId | default "unknown" }}"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PYTHONUNBUFFERED
              value: "1"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting agent variation {{ .Values.variationId | default "0" }} for run {{ .Values.runId | default "unknown" }}"
              echo "Repository: {{ .Values.repoUrl | default "" }}"
              echo "Prompt: {{ .Values.prompt | default "" }}"
              python -u /agent/main.py
          resources:
            {{- toYaml .Values.agents.resources | nindent 12 }}
      backoffLimit: 0