apiVersion: apps/v1
kind: Deployment
metadata:
  name: aideator-fastapi
  labels:
    {{- include "aideator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aideator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aideator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "aideator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until nc -z chart-aideator-postgresql 5432; do
                echo "PostgreSQL is not ready - sleeping"
                sleep 2
              done
              echo "PostgreSQL is ready!"
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "Running database migrations..."
              
              # Wait for database to be truly ready (not just accepting connections)
              for i in {1..30}; do
                if python -c "import asyncio; from sqlalchemy import text; from sqlalchemy.ext.asyncio import create_async_engine; engine = create_async_engine('$DATABASE_URL'); asyncio.run(engine.dispose())"; then
                  echo "Database connection successful"
                  break
                fi
                echo "Database not ready, attempt $i/30..."
                sleep 2
              done
              
              # Run migrations
              echo "Running alembic upgrade head..."
              python -m alembic upgrade head
              
              if [ $? -eq 0 ]; then
                echo "Migrations completed successfully!"
              else
                echo "Migration failed!"
                exit 1
              fi
          env:
            - name: DATABASE_URL
              value: {{ .Values.database.url }}
            - name: DEBUG
              value: "{{ .Values.config.debug }}"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aideator-secret
                  key: secret-key
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: aideator-secret
                  key: encryption-key
            - name: REDIS_URL
              value: "redis://chart-redis-master:6379/0"
            # Use placeholder API keys to satisfy validation during migration
            - name: OPENAI_API_KEY
              value: "sk-placeholder-for-migrations-only-00000000000000000000"
            - name: ANTHROPIC_API_KEY
              value: "sk-ant-placeholder-for-migrations-only-000000000000000"
            - name: GEMINI_API_KEY
              value: "AIzaPlaceholderForMigrationsOnly00000000000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel }}
            - name: DEBUG
              value: "{{ .Values.config.debug }}"
            - name: API_V1_PREFIX
              value: {{ .Values.config.apiV1Prefix }}
            - name: MAX_VARIATIONS
              value: "{{ .Values.config.maxVariations }}"
            - name: DATABASE_URL
              value: {{ .Values.database.url }}
            # SECURITY TRADEOFF: Using hardcoded Redis URL for development simplicity
            # In production, use ConfigMap or Secret for Redis credentials
            - name: REDIS_URL
              value: "redis://chart-redis-master:6379/0"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AGENT_IMAGE
              value: "{{ .Values.agentImage.repository }}:{{ .Values.agentImage.tag }}"
            # API keys stored in database, not environment variables
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aideator-secret
                  key: secret-key
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: aideator-secret
                  key: encryption-key
            # GitHub OAuth configuration (required)
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-oauth-secret
                  key: client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-oauth-secret
                  key: client-secret
            # Provide API keys from secrets if they exist
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api-key
                  optional: true
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: anthropic-secret
                  key: api-key
                  optional: true
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-secret
                  key: api-key
                  optional: true
            {{- if .Values.env }}
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /app/data
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "aideator.fullname" . }}-data
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}