apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aideator.fullname" . }}
  labels:
    {{- include "aideator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aideator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aideator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "aideator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel }}
            - name: DEBUG
              value: "{{ .Values.config.debug }}"
            - name: API_V1_PREFIX
              value: {{ .Values.config.apiV1Prefix }}
            - name: MAX_VARIATIONS
              value: "{{ .Values.config.maxVariations }}"
            - name: DATABASE_URL
              value: {{ .Values.database.url }}
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AGENT_IMAGE
              value: "{{ .Values.agentImage.repository }}:{{ .Values.agentImage.tag }}"
            # OpenRouter removed - using LiteLLM with direct OpenAI SDK
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.openai.name }}
                  key: {{ .Values.secrets.openai.key }}
                  optional: {{ .Values.secrets.openai.optional | default true }}
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.anthropic.name }}
                  key: {{ .Values.secrets.anthropic.key }}
                  optional: {{ .Values.secrets.anthropic.optional | default true }}
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.gemini.name }}
                  key: {{ .Values.secrets.gemini.key }}
                  optional: {{ .Values.secrets.gemini.optional | default true }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aideator-secret
                  key: secret-key
            {{- if .Values.env }}
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /app/data
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "aideator.fullname" . }}-data
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}