apiVersion: v1
kind: Service
metadata:
  name: {{ include "aideator.fullname" . }}-litellm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aideator.labels" . | nindent 4 }}
    app.kubernetes.io/component: litellm-gateway
spec:
  type: {{ .Values.litellm.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.litellm.service.port | default 4000 }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.litellm.service.type "NodePort") .Values.litellm.service.nodePort }}
      nodePort: {{ .Values.litellm.service.nodePort }}
      {{- end }}
  selector:
    {{- include "aideator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: litellm-gateway