apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aideator.fullname" . }}-litellm-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aideator.labels" . | nindent 4 }}
    app.kubernetes.io/component: litellm-gateway
data:
  config.yaml: |
    model_list:
      - model_name: gpt-4o-mini
        litellm_params:
          model: openai/gpt-4o-mini
          api_key: os.environ/OPENAI_API_KEY
      - model_name: gpt-4
        litellm_params:
          model: openai/gpt-4
          api_key: os.environ/OPENAI_API_KEY
      - model_name: gpt-3.5-turbo
        litellm_params:
          model: openai/gpt-3.5-turbo
          api_key: os.environ/OPENAI_API_KEY
      {{- if .Values.secrets.anthropic }}
      - model_name: claude-3-opus
        litellm_params:
          model: anthropic/claude-3-opus-20240229
          api_key: os.environ/ANTHROPIC_API_KEY
      - model_name: claude-3-sonnet
        litellm_params:
          model: anthropic/claude-3-sonnet-20240229
          api_key: os.environ/ANTHROPIC_API_KEY
      - model_name: claude-3-haiku
        litellm_params:
          model: anthropic/claude-3-haiku-20240307
          api_key: os.environ/ANTHROPIC_API_KEY
      {{- end }}
      {{- if .Values.litellm.models }}
      {{- range .Values.litellm.models }}
      - model_name: {{ .name }}
        litellm_params:
          model: {{ .model }}
          {{- if .api_key }}
          api_key: {{ .api_key }}
          {{- end }}
          {{- if .api_base }}
          api_base: {{ .api_base }}
          {{- end }}
          {{- if .api_version }}
          api_version: {{ .api_version }}
          {{- end }}
      {{- end }}
      {{- end }}
    
    general_settings:
      master_key: os.environ/LITELLM_MASTER_KEY
      {{- if .Values.litellm.database.enabled }}
      database_url: {{ .Values.litellm.database.url | quote }}
      {{- else }}
      database_url: "sqlite:///litellm_proxy.db"
      {{- end }}
      {{- if .Values.litellm.cache.enabled }}
      cache: true
      cache_params:
        type: redis
        host: {{ include "aideator.fullname" . }}-redis
        port: 6379
        {{- if .Values.litellm.cache.ttl }}
        ttl: {{ .Values.litellm.cache.ttl }}
        {{- end }}
      {{- end }}
      {{- if .Values.litellm.callbacks }}
      callbacks: {{ .Values.litellm.callbacks | toJson }}
      {{- else }}
      callbacks: ["prometheus"]
      {{- end }}
      
    litellm_settings:
      drop_params: false
      set_verbose: {{ .Values.litellm.verbose | default false }}
      {{- if .Values.litellm.timeout }}
      request_timeout: {{ .Values.litellm.timeout }}
      {{- end }}
      
    router_settings:
      model_group_alias:
        "gpt-4o-mini": "gpt-4o-mini"
        "gpt-4": "gpt-4"
        "gpt-3.5-turbo": "gpt-3.5-turbo"
        {{- if .Values.secrets.anthropic }}
        "claude-3-opus": "claude-3-opus"
        "claude-3-sonnet": "claude-3-sonnet"
        "claude-3-haiku": "claude-3-haiku"
        {{- end }}