apiVersion: v1
kind: Service
metadata:
  name: aideator-fastapi-svc
  labels:
    {{- include "aideator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "aideator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: fastapi