apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aideator.fullname" . }}-litellm-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aideator.labels" . | nindent 4 }}
    app.kubernetes.io/component: litellm-gateway
type: Opaque
data:
  master-key: {{ .Values.litellm.masterKey | default "sk-1234" | b64enc }}