{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aideator.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aideator.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "aideator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}