[project]
name = "aideator"
version = "0.1.0"

[project.entry-points."dagger.mod"]
main_object = "main:Aideator"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
only-include = ["main.py", "__init__.py"]