apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5005
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: k3d-aideator
product: k3d
registry: ctlptl-registry
k3d:
  v1alpha5Simple:
    metadata:
      name: aideator
    servers: 1
    agents: 2
    ports:
      # API Server
      - port: 8000:8000
        nodeFilters:
          - loadbalancer
      # Redis
      - port: 6379:6379
        nodeFilters:
          - loadbalancer
      # PostgreSQL
      - port: 5432:5432
        nodeFilters:
          - loadbalancer
      # LiteLLM
      - port: 4000:4000
        nodeFilters:
          - loadbalancer
      # HTTP/HTTPS (for ingress if needed)
      - port: 80:80
        nodeFilters:
          - loadbalancer
      - port: 443:443
        nodeFilters:
          - loadbalancer
    options:
      k3s:
        extraArgs:
          - arg: --disable=traefik
            nodeFilters:
              - server:*
    registries:
      config: |
        mirrors:
          "localhost:5005":
            endpoint:
              - http://ctlptl-registry:5000