# AIdeator Secrets Configuration
# This file defines the secrets structure for different environments

# Development Environment
development:
  namespace: aideator
  secrets:
    - name: aideator-secret
      type: generic
      data:
        secret-key: "${SECRET_KEY:-}"
        encryption-key: "${ENCRYPTION_KEY:-}"
    
    - name: openai-secret
      type: generic
      data:
        api-key: "placeholder"
    
    - name: anthropic-secret
      type: generic
      data:
        api-key: "placeholder"
    
    - name: gemini-secret
      type: generic
      data:
        api-key: "placeholder"
    
    - name: database-secret
      type: generic
      data:
        url: "${DATABASE_URL:-postgresql://postgres:postgres@aideator-postgresql:5432/aideator}"
        password: "${DATABASE_PASSWORD:-aideator123}"
    
    - name: redis-secret
      type: generic
      data:
        url: "${REDIS_URL:-redis://aideator-redis:6379}"
    
    - name: litellm-secret
      type: generic
      data:
        master-key: "${LITELLM_MASTER_KEY:-sk-1234}"

# Production Environment
production:
  namespace: aideator
  secrets:
    - name: aideator-secret
      type: generic
      data:
        secret-key: "${SECRET_KEY}"
        encryption-key: "${ENCRYPTION_KEY}"
    
    - name: openai-secret
      type: generic
      data:
        api-key: "${OPENAI_API_KEY}"
    
    - name: anthropic-secret
      type: generic
      data:
        api-key: "${ANTHROPIC_API_KEY}"
    
    - name: gemini-secret
      type: generic
      data:
        api-key: "${GEMINI_API_KEY}"
    
    - name: database-secret
      type: generic
      data:
        url: "${DATABASE_URL}"
        password: "${DATABASE_PASSWORD}"
    
    - name: redis-secret
      type: generic
      data:
        url: "${REDIS_URL}"
    
    - name: litellm-secret
      type: generic
      data:
        master-key: "${LITELLM_MASTER_KEY}"

# Staging Environment
staging:
  namespace: aideator-staging
  secrets:
    - name: aideator-secret
      type: generic
      data:
        secret-key: "${SECRET_KEY}"
        encryption-key: "${ENCRYPTION_KEY}"
    
    - name: openai-secret
      type: generic
      data:
        api-key: "${OPENAI_API_KEY}"
    
    - name: anthropic-secret
      type: generic
      data:
        api-key: "${ANTHROPIC_API_KEY}"
    
    - name: gemini-secret
      type: generic
      data:
        api-key: "${GEMINI_API_KEY}"
    
    - name: database-secret
      type: generic
      data:
        url: "${DATABASE_URL}"
        password: "${DATABASE_PASSWORD}"
    
    - name: redis-secret
      type: generic
      data:
        url: "${REDIS_URL}"
    
    - name: litellm-secret
      type: generic
      data:
        master-key: "${LITELLM_MASTER_KEY}"